title: Cedric Vicera
author: Cedric Vicera
#email:
#lang: zh
#description:
#url: https://www.cedricvicera.com # the base hostname & protocol for your site, e.g. http://example.com

username: cedricvicera

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: light

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
