title: Mint
author: Author
email: your-email@example.com
description: A clean and responsive jekyll theme

github_username: cedricvicera
twitter_username: cedricvicera
instagram_username: cedricvicera
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:
remote_theme: jekyll-theme-mint
blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
