title: Mint
author: Cedric Vicera
email: catwithpiano@gmail.com
#description: A blog 

github_username: cedricvicera
twitter_username: cedricvicera
instagram_username: cedricvicera

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
