title: Cedric Vicera
#author: Author
email: cedric@cedricvicera.com
description: Cedric Vicera

github_username: cedricvicera
twitter_username: cedricvicera
#instagram_username: cedricvicera

url: "https://www.cedricvicera.com"
baseurl: ""

date_format: '%b %-d, %Y'

# google_analytics:
# disqus_shortname:
remote_theme: jekyll-theme-mint
blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
