title: Cedric Vicera
author: Cedric Vicera
url: "https://cedricvicera.com"
permalink: /:title
#email:
#lang: en
#description:
#url: https://www.cedricvicera.com # the base hostname & protocol for your site, e.g. http://example.com

username: cedricvicera
github_username: cedricvicera
youtube_username: cedricvicera
instagram_username: cedricvicera
twitter_username: cedricvicera

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: light

markdown: kramdown
kramdown:
  input: GFM

plugins:
 - jekyll-feed
 - jekyll-seo-tag

 
