title: Cedric Vicera
author: Cedric Vicera
email: cedric@cedricvicera.com
#lang: zh
#description:
#url: https://www.cedricvicera.com # the base hostname & protocol for your site, e.g. http://example.com

github_username: cedricvicera
twitter_username: cedricvicera
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
