title: Cedric Vicera
author: Cedric Vicera
email: cedric@cedricvicera.com
description: Cedric Vicera

github_username: aidewoode
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: dark

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
