baseURL = "https://www.cedricvicera.com"
publishDir = "docs"
languageCode = "en-us"
title = "Hadi Sinaee"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  subtitle= "PhD Student"
  interests="Deep Reinforcement Learning, Machine Learning "
  cv_name= "HadiSinaee_CV.pdf"
  blog="http://myblog.edu"

[[params.affilation]]
  name = "Stanford University"
  position = "PhD Student"
  contact = "hadi@cs.stanford.edu"

[[params.affilation]]
  name = "MyCoolStartup"
  position = "Co-Founder"
  contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/hadisinaee"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/hadisinaee"
