baseURL = "https://www.cedricvicera.com"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-us"
title = "Cedric Vicera"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000

[params]
  interests="Philosophy of Science, Machine Learning"
  cv_name= "vicera_cv.pdf"
  #blog="http://myblog.edu"

[[params.affilation]]
  name = "University of Arizona"
  position = "BA Student"
  contact = "spencervicera@email.arizona.edu"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/cedricvicera"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/cedricvicera"

  [[params.social]]
    name = "Instagram"
    icon = "instagram"
    url = "https://www.instagram.com/cedricvicera"

[[params.introduction.paragraph]]
  text="""I study Philosophy at the University of Arizona.
  Currently, I’m a research assistant in the Computational Medicine and Informatics Collaboratory and the University of Arizona Genetics Core.
  In addition, I’m a head section leader in the School of Information where I teach introductory Python programming.
  I’m writing an honors thesis in Philosophy advised by Richard Healey.
   """
